config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  get 'tops/index'

  get 'tops/show'
  
  resources :articles
  resources :contacts
  resources :links
  resources :tops

end

app/models/article.rb
class Article < ActiveRecord::Base
    def self.search(search)
        if search
            Article.where(['title LIKE ?', "%#{search}%"])
        else
            Article.all
        end
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    def self.search(search)
        if search
            Contact.where(['article_type LIKE ?', "%#{search}%"])
        else
            Contact.all
        end
    end
end

app/models/top.rb
class Top < ActiveRecord::Base
    def self.search(search)
        if search
            Top.where(['semester LIKE ?', "#{search}"])
        else
            Top.all
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    tops_index_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	#記事一覧
	def index
		@articles = Article.all
		@articles = Article.search(params[:search])
	end

	def show
		@articles = Article.all
		@article = Article.find(params[:id])
	end

	def new
		@articles = Article.all
		@article = Article.new
	end

	def edit
		@articles = Article.all
		@article = Article.find(params[:id])
	end

	def create
		@articles = Article.all
		@article = Article.new(article_params)
		if @article.save
			redirect_to articles_path, notice: "新しいお知らせを登録しました。"
		else
			render "new"
		end
	end
	
	def article_params
		params.require(:article).permit(:title, :text, :released_at)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
        @contacts = Contact.all
        @articles = Article.all
        @contacts = Contact.search(params[:search])
    end
    
    def new
        @contact = Contact.new
        @articles = Article.all
    end

    def create
        @articles = Article.all
        @contact = Contact.new(contact_params)
        if @contact.save
            redirect_to contacts_path, notice: "講義情報を登録しました。"
        else
            render :new
        end
    end
    
    def contact_params
        params.require(:contact).permit(:article_type, :class_name, :class_place, :remark, :arrival_date, :published_at)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    def index
        @articles = Article.all
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @articles = Article.all
    @tops = Top.search(params[:search])
    @contacts = Contact.all
  end

  def show
    @articles = Article.all
  end
  
  def new
    @articles = Article.all
    @top = Top.new
  end
  
  def create
    @articles = Article.all
    @top = Top.new(top_params)
		if @top.save
			redirect_to tops_path, notice: "新しい講義を登録しました。"
		else
			render "new"
		end
  end
  
  def top_params
		params.require(:top).permit(:class_type, :class_name, :class_place, :period, :weekday, :semester)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    @articles = Article.all
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/articles/_form.html.erb
<table class="table table-striped">
  <tr>
    <th><%= form.label :title %></th>
    <td><%= form.text_field :title, size: 20 %></td>
  </tr>
  <tr>
    <th><%= form.label :text %></th>
    <td><%= form.text_area :text, rows: 20, cols: 50 %></td>
  </tr>
  <tr>
    <th><%= form.label :released_at, for: "article_released_at_1i" %></th>
    <td><%= form.datetime_select :released_at, start_year: 2000, end_year: Time.now.year + 1, use_month_numbers: true %></td>
  </tr>

</table>

app/views/articles/index.html.erb
<% @pagetitle = "お知らせ" %>

<div class="art art_search">
	<p class="search_form">
		<%= form_tag articles_path, :method => 'get' do %>
			<span><%= submit_tag " ", :name => nil, :class => "search_btn", :id => "submit" %></span>
			<%= text_field_tag :search, params[:search], :placeholder => "キーワード検索", :class => "search", :id => "text" %>
		<% end %>
		<%= form_tag articles_path, :method => 'get' do %>
			<%= hidden_field_tag :search, params[:search], :value => nil %>
			<%= submit_tag "", :name => nil, :id => "cancel", :class => "cancel" %>
		<% end %>
	</p>
</div>

<div class="art_sent">
	<% if @articles.present? %>
		<p class="check">未読</p>
		<div class="articles">
			<% @articles.order('id desc').each do |article| %>
				<% if article.checked == false %>
					<div class="art">
						<span class="checked"></span>
						<div class="article_title"><%= link_to article.title, article , :class => "article_link" %></div>
						<div class="article_time">追加日：<%= article.released_at.strftime("%Y/%m/%d %H:%M") %></div>
					</div>
				<% end %>
			<% end %>
		</div>
		<p class="check">既読</p>
		<div class="articles">
			<% @articles.order('id desc').each do |article| %>
				<% if article.checked == true %>
					<div class="art">
						<div class="article_title"><%= link_to article.title, article , :class => "article_link" %></div>
						<div class="article_time">追加日：<%= article.released_at.strftime("%Y/%m/%d %H:%M") %></div>
					</div>
				<% end %>
			<% end %>
		</div>
	<% else %>
		<p>お知らせがありません。</p>
	<% end %>
</div>
<!--
<div>
	<% if current_user %>
		<p><%= link_to "新規作成", :new_article , :class => "new_article" %></p>
	<% end %>
</div>
-->

app/views/articles/new.html.erb
<% @pagetitle = "お知らせの新規登録" %>

<%= form_for @article do |form| %>
<%= render "form", form: form %>
    <p><%= form.submit %></p>
<% end %>

app/views/articles/show.html.erb
<% @pagetitle = "お知らせ" %>
<div class="article">
    <div class="art_show">
        <span class="art_tit">詳細</span>
        <div class="art_cont">
            <h2><%= @article.title %></h2>
            <p class="released">追加日：<%= @article.released_at.strftime("%Y/%m/%d %H:%M") %></p>
            <p class="show_text"><%= @article.text %></p>
        </div>
    </div>
</div>

app/views/contacts/_form.html.erb
<div>
    <%= form.label :article_type, "お知らせの種類" %>
    <%= form.select :article_type, [["休講","rest"],["補講","extra"],["変更","change"]], :prompt => "選択してください" %>
</div>
<div>
    <%= form.label :class_name, "講義名" %>
    <%= form.text_field :class_name %>
</div>
<div>
    <%= form.label :arribal_date, "変更日" %>
    <%= form.date_select :arrival_date %>
</div>
<div>
    <%= form.label :class_place, "変更後の教室" %>
    <%= form.text_field :class_place %>
</div>
<div>
    <%= form.label :remark, "備考" %>
    <%= form.text_area :remark %>
</div>
<div>
    <%= form.label :published_at, "公開日" %>
    <%= form.datetime_select :published_at, start_year: 2000, end_year: Time.now.year + 1, use_month_numbers: true %>
</div>

app/views/contacts/index.html.erb
<% @pagetitle = "講義連絡" %>

<div id="contact">
    <div class="contact_content">
        <% if @contacts.present? %>
            <h3>今日の講義連絡</h3>
            <div class="daily">
                <div class="content">
                    <div class="slider single-item">
                        <% @contacts.each do |contact| %>
                            <% if contact.arrival_date == Date.today %>
                                <div>
                                    <p>
                                        <% if contact.article_type == 'rest' %>休講：
                                        <% elsif contact.article_type == 'extra' %>補講：
                                        <% else %>変更：
                                        <% end %>
                                        <%= contact.class_name %>
                                    </p>
                                    <p class="remark"><%= contact.remark %></p>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>

            <h4 id="rest1">休講</h4>
            <div class="change">
                <% @contacts.order('arrival_date asc').each do |contact| %>
                    <% if contact.arrival_date >= Date.today && contact.class_name.present? %>
                        <% if contact.article_type == "rest" %>
                            <div class="cont">
                                <div class="cont_in">
                                    <div>
                                        <%= contact.class_name %>
                                        <span><%= contact.arrival_date %></span>
                                    </div>
                                    <div class="remark"><%= contact.remark %></div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
            <h4 id="extra1">補講</h4>
            <div class="change">
                <% @contacts.order('arrival_date asc').each do |contact| %>
                    <% if contact.arrival_date >= Date.today && contact.class_name.present? %>
                        <% if contact.article_type == "extra" %> 
                            <div class="cont">
                                <div class="cont_in">
                                    <div>
                                        <%= contact.class_name %>
                                        <span><%= contact.arrival_date %></span>
                                    </div>
                                    <% if contact.class_place.present? %>
                                        <div><%= contact.class_place %>教室</div>
                                    <% end %>
                                    <div class="remark"><%= contact.remark %></div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
            <h4 id="change1">変更</h4>
            <div class="change">
                <% @contacts.order('arrival_date asc').each do |contact| %>
                    <% if contact.arrival_date >= Date.today && contact.class_name.present? %>
                        <% if contact.article_type == "change" %>
                            <div class="cont">
                                <div class="cont_in">
                                    <div>
                                        <%= contact.class_name %>
                                        <span><%= contact.arrival_date %></span>
                                    </div>
                                    <% if contact.class_place.present? %>
                                        <div>変更後：<%= contact.class_place %>教室</div>
                                    <% end %>
                                    <div class="remark"><%= contact.remark %></div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        <% else %>
            <p>講義連絡はありません。</p>
        <% end %>
        <!--
        <%= link_to "登録", new_contact_path, :class => "new" %>
        -->
    </div>
</div>

app/views/contacts/new.html.erb
<% @pagetitle = "講義連絡の新規登録" %>

<div class="contents">
    <%= form_for @contact do |form| %>
        <%= render "form", form: form %>
        <p><%= form.submit "登録" %></p>
    <% end %>
</div>


<%= link_to "一覧に戻る", contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portal | Senshu Uni.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
</head>
<body>
  <div id="header">
    <%= render "shared/header" %>
  </div>

  <div id="contents">
    <%= yield %>
  </div>
  
  <% if current_user %>
    <div id="footer">
      <%= render "shared/footer" %>
    </div>
  <% end %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/links/index.html.erb
<% @pagetitle = "リンク" %>
<div class="list">
    <p>
        <a href="https://twitter.com/?lang=ja">
            <span><%= image_tag 'twitter.jpg', :class => "img" %></span>
            <label class="list_text">Twitter</label>
        </a>
    </p>
    <p>
        <a href="https://direct4b.com/signin/">
            <span><%= image_tag 'direct.png', :class => "img" %></span>
            <label class="list_text">direct</label>
        </a>
    </p>
    <p>
        <a href="http://mail.senshu-u.jp/">
            <span><%= image_tag 'Gmail.gif', :class => "img" %></span>
            <label class="list_text">専修大学Gmail</label>
        </a>
    </p>
    <p>
        <a href="https://cp.ss.senshu-u.ac.jp/lms/">
            <span><%= image_tag 'coursepower.gif', :class => "img" %></span>
            <label class="list_text">CoursePower</label>
        </a>
    </p>
    <p>
        <a href="https://s-net.acc.senshu-u.ac.jp/career/index.jsp">
            <span><%= image_tag 'Snet.gif', :class => "img" %></span>
            <label class="list_text">就職支援システム S-net</label>
        </a>
    </p>
    <p>
        <a href="https://syllabus.acc.senshu-u.ac.jp/syllabus/syllabus/search/Menu.do">
            <span><%= image_tag 'syllabus.gif', :class => "img" %></span>
            <label class="list_text">Webシラバス</label>
        </a>
    </p>
    <p>
        <a href="https://www.career-note.jp/" class="list_last">
            <span><%= image_tag 'webcarrier.gif', :class => "img" %></span>
            <label class="list_text">Webキャリアノート</label>
        </a>
    </p>
</div>

app/views/shared/_footer.html.erb
<% @article_count = 0 %>
<% @articles.each do |article| %>
    <% if article.checked == false %>
        <% @article_count += 1 %>
    <% end %>
<% end %>

<ul>
    <li>
        <% if @pagetitle == 'スケジュール' %>
            <%= image_tag("top_color.png", :class => "footer_img") %>
            <%= link_to "スケジュール", tops_index_path, :class => "foot-navi-on" %>
        <% else %>
            <%= image_tag("top.png", :class => "footer_img") %>
            <%= link_to "スケジュール", tops_index_path, :class => "foot-navi" %>
        <% end %>
    </li>
    <li>
        <% if @article_count > 0 then %> 
            <label class="article_count"><%= @article_count %></label>
        <% end %>
        <% if @pagetitle == 'お知らせ' %>
            <%= image_tag("article_color.png", :class => "footer_img") %>
            <%= link_to "お知らせ", articles_path, :class => "foot-navi-on" %>
        <% else %>
            <%= image_tag("article.png", :class => "footer_img") %>
            <%= link_to "お知らせ", articles_path, :class => "foot-navi" %>
        <% end %>
    </li>
    <li>
        <% if @pagetitle == '講義連絡' %>
            <%= image_tag("contact_color.png", :class => "footer_img") %>
            <%= link_to "講義連絡", contacts_path, :class => "foot-navi-on" %>
        <% else %>
            <%= image_tag("contact.png", :class => "footer_img") %>
            <%= link_to "講義連絡", contacts_path, :class => "foot-navi" %>
        <% end %>
    </li>
    <li>
        <% if @pagetitle == 'リンク' %>
            <%= image_tag("link_color.png", :class => "footer_img") %>
            <%= link_to "リンク", links_path, :class => "foot-navi-on" %>
        <% else %>
            <%= image_tag("link.png", :class => "footer_img") %>
            <%= link_to "リンク", links_path, :class => "foot-navi" %>
        <% end %>
        
    </li>
    <li>
        <% if @pagetitle == '設定' %>
            <%= image_tag("setting_color.png", :class => "footer_img") %>
            <%= link_to "設定", edit_user_registration_path, :class => "foot-navi-on" %>
        <% else %>
            <%= image_tag("setting.png", :class => "footer_img") %>
            <%= link_to "設定", edit_user_registration_path, :class => "foot-navi" %>
        <% end %>
        
    </li>
</ul>

app/views/shared/_header.html.erb
<p><%= @pagetitle %></p>
<% if current_user %>
    <div>
        <%= link_to "ログアウト", destroy_user_session_path, :method => :delete, :class => "logout_button" %>
    </div>
<% end %>

app/views/tops/_form.html.erb
<% @pagetitle = "講義の新規登録" %>

<div>
    <%= form.label :class_name, "講義名" %>
    <%= form.text_field :class_name, size: 30 %>
</div>

<div>
    <%= form.label :class_type, "種類" %>
    <ul>
        <li><%= form.radio_button :class_type, "専門科目" %>専門科目</li>
        <li><%= form.radio_button :class_type, "一般教養" %>一般教養科目</li>
        <li><%= form.radio_button :class_type, "資格科目" %>資格科目</li>
    </ul>
</div>

<div>
    <%= form.label :class_place, "教室" %>
    <%= form.text_field :class_place, size: 30 %>
</div>

<div>
    <%= form.label :weekday, "曜日" %>
    <%= form.radio_button :weekday, 1 %>月
    <%= form.radio_button :weekday, 2 %>火
    <%= form.radio_button :weekday, 3 %>水
    <%= form.radio_button :weekday, 4 %>木
    <%= form.radio_button :weekday, 5 %>金
    <%= form.radio_button :weekday, 6 %>土
</div>

<div>
    <%= form.label :period, "時限" %>
    <%= form.radio_button :period, 1 %>１
    <%= form.radio_button :period, 2 %>２
    <%= form.radio_button :period, 3 %>３
    <%= form.radio_button :period, 4 %>４
    <%= form.radio_button :period, 5 %>５
    <%= form.radio_button :period, 6 %>６
</div>
<div>
    <%= form.label :semester, "学期" %>
    <%= form.radio_button :semester, 0 %>前期
    <%= form.radio_button :semester, 1 %>後期
</div>

app/views/tops/index.html.erb
<div id="contents" class="tops">
  <% @pagetitle = "スケジュール" %>
  <% d =  Date.today %>
  <% weekday = %w[日 月 火 水 木 金 土] %>
  <% w = 0 %>
  <% contact_count = 0 %>
  <% period_time = ['9:00〜10:30', '10:45〜12:15', '13:05〜14:35', '14:50〜16:20', '16:35〜18:05', '18:15〜19:45'] %>

  <% if params[:commit] == "後期" %>
    <div id="semester_btn">
      <%= form_tag tops_path, :method => 'get' do %>
        <%= submit_tag "前期", :id => "submit", :class => "btn btn1" %>
        <%= hidden_field_tag :search, params[:search], :value => 0 %>
      <% end %>
    </div>
    <div id="semester_btn">
      <%= form_tag tops_path, :method => 'get' do %>
        <%= submit_tag "後期", :id => "submit", :class => "btn btn2 checked" %>
        <%= hidden_field_tag :search, params[:search], :value => 1 %>
      <% end %>
    </div>
  <% else %>
    <div id="semester_btn">
      <%= form_tag tops_path, :method => 'get' do %>
        <%= submit_tag "前期", :id => "submit", :class => "btn btn1 checked" %>
        <%= hidden_field_tag :search, params[:search], :value => 0 %>
      <% end %>
    </div>
    <div id="semester_btn">
      <%= form_tag tops_path, :method => 'get' do %>
        <%= submit_tag "後期", :id => "submit", :class => "btn btn2" %>
        <%= hidden_field_tag :search, params[:search], :value => 1 %>
      <% end %>
    </div>
  <% end %>

  
  <% if @tops.present? %>
    <div class="schedule today">
      <h3 class="da">今日の講義</h3>
      <% @tops.order('period asc').each do |top| %>
        <% if d.wday == top.weekday %>
         <div class="coma">
           <div>
             <span>
               <%= top.period %>限
               ：<%= period_time[top.period - 1] %>
             </span>
             <span class="place"><%= top.class_place %>教室</span>
             <div><%= top.class_name %></div>
           </div>
          </div>
        <% end %>
      <% end %>
      <% @contacts.each do |contact| %>
        <% if d == contact.arrival_date %>
          <% contact_count += 1 %>
        <% end %>
      <% end %>
      <% if contact_count > 0 %>
        <p class="contact_s">※<%= link_to  "講義連絡あり", contacts_path, :class => "contact" %></p>
      <% end %>
    </div>
    <div class="schedule weekly">
      <h3>週間スケジュール</h3>
      <% @tops.order('weekday asc').each do |top| %>
        <% if !(w == top.weekday) %>
          <h4><%= weekday[top.weekday] %>曜日</h4>
        <% end %>
        <div class="coma">
          <div>
            <span>
              <%= top.period %>限
              ：<%= period_time[top.period - 1] %>
            </span>
            <span class="place"><%= top.class_place %>教室</span>
            <div><%= top.class_name %></div>
          </div>
        </div>
        <% w = top.weekday %>
      <% end %>
    </div>
  <% else %>
    <p>講義情報がありません。</p>
  <% end %>
  <!--
  <p class="new"><%= link_to "新規登録", :new_top %></p>
  -->
</div>

app/views/tops/new.html.erb
<% @pagetitle = "講義の新規登録" %>
<div class="tops_new">
    <%= form_for @top do |form| %>
    <%= render "form", form: form %>
        <p class="submit_btn"><%= form.submit "登録" %></p>
    <% end %>
</div>

app/views/tops/show.html.erb
<h1>Tops#show</h1>
<p>Find me in app/views/tops/show.html.erb</p>